tfidf/main/urls.py
from django.urls import path
from .views import index, file_to_analysis


app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('analisys/<int:id>/', file_to_analysis, name='file_to_analysis')
]

tfidf/tfidf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tfidf/main/models.py
from django.db import models
from .utils import get_text_content


class Word(models.Model):
    name = models.CharField(max_length=256, verbose_name='Word', db_index=True)
    count_of_documents = models.IntegerField(verbose_name='Count of documents with the word', default=1)

    class Meta:
        verbose_name = 'Word'
        verbose_name_plural = 'Words'
        ordering = ['name']

    def __str__(self):
        return self.name


class FileForAnalysis(models.Model):
    upload = models.FileField(upload_to='media/%Y/%m/%d', verbose_name='File')
    upload_at = models.DateTimeField(auto_now_add=True, verbose_name='Upload_at')

    class Meta:
        verbose_name = 'File'
        verbose_name_plural = 'Files'
        ordering = ['-upload_at']

    def save(self, *args, **kwargs):
        instance = super(FileForAnalysis, self).save(*args, **kwargs)
        self.update_word_list()
        return instance

    def update_word_list(self):
        text_content = get_text_content(self)
        words = set(text_content.split())
        for word in words:
            try:
                saved_word = Word.objects.get(name=word)
                saved_word.count_of_documents += 1
                saved_word.save()
            except:
                new_word = Word(name=word, count_of_documents=1)
                new_word.save()

tfidf/main/forms.py
from django import forms
from .models import FileForAnalysis


class DocumentForm(forms.ModelForm):
    class Meta:
        model = FileForAnalysis
        fields = ('upload', )
        widgets = {'upload': forms.FileInput(attrs={'class': 'form-control'})}
        labels = {'upload': '', }

tfidf/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import FileForAnalysis, Word
from .forms import DocumentForm
from .utils import get_text_content
from collections import Counter


def index(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            file = form.save(commit=False)
            file.save()
            return redirect('main:file_to_analysis', id=file.id)
    else:
        form = DocumentForm()
    return render(request, 'main/index.html', {
        'form': form,
    })


def file_to_analysis(request, id):
    documents_all = FileForAnalysis.objects.count()
    file = get_object_or_404(FileForAnalysis, id=id)
    text = get_text_content(file).split()
    text_counter = Counter(text).most_common(50)

    words = {}

    for word in text_counter:
        word_to_list = get_object_or_404(Word, name=word[0])
        word_idf = round(word_to_list.count_of_documents / documents_all, 4)
        words.update({word[0]: (word[1], word_idf)})

    sort_dic = sorted(words.items(), key=lambda dicx: dicx[1][1], reverse=True)
    sort_dic = dict(sort_dic)

    return render(request, 'main/analysis.html', context={'words': sort_dic})

tfidf/main/templates/main/analysis.html
{% extends "main/base.html" %}

{% block content %}
<div class="container">
    <h3 class="topic">Results of TF-IDF analysis</h3>
</div>
<div class="container-sm px-4 gx-5">
    <table class="table table-striped table-hover table-sm analysis">
        <caption>TF-IDF analysis</caption>
        <thead class="table-dark">
        <th scope="col">Word</th>
        <th scope="col">TF</th>
        <th scope="col">IDF</th>
        </thead>
        <tbody>
        {% for key, val in words.items %}
        <tr>
            <td>{{ key }}</td>
            {% for indx in val %}
            <td>{{ indx }}</td>
            {% endfor %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

tfidf/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>TF-IDF</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:index' %}">TF-IDF ANALYSIS</a>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

tfidf/main/templates/main/index.html
{% extends "main/base.html" %}

{% block content %}
<div class="w-75 p-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
</div>

{% endblock %}